packages:
  - 'packages/uemoa'
  - 'packages/__tests__/project1'
  - 'packages/utils/vitest'
  - 'packages/tansolid'
  - 'apps/uemoa-viewer'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/dev-utils@0.8.2'
