/**
 * SYSCOHADA — CLASS 8: Non-Ordinary Activity Accounts — HAO
 * (Class 8: Non-Ordinary Activity Accounts — HAO)
 *
 * Covers: book value of disposed assets, proceeds from asset disposals,
 * extraordinary charges, extraordinary income, HAO provisions and reversals,
 * employee profit-sharing, balancing grants, and income tax.
 *
 * Source: Official SYSCOHADA Chart of Accounts PDF, pages 44–46.
 */
import type { Plan } from './types';

export const class8Accounts = {
  // ────────── 81 NET BOOK VALUE OF FIXED ASSETS DISPOSED OF ──────────
  81: "NET BOOK VALUE OF FIXED ASSETS DISPOSED OF (HAO CHARGE) D'IMMOBILISATIONS",
  811: 'NET BOOK VALUE OF DISPOSED INTANGIBLE ASSETS',
  812: 'NET BOOK VALUE OF DISPOSED TANGIBLE ASSETS',
  816: 'NET BOOK VALUE OF DISPOSED FINANCIAL ASSETS',

  // ────────── 82 PROCEEDS FROM DISPOSAL OF FIXED ASSETS ──────────
  82: "PROCEEDS FROM DISPOSAL OF FIXED ASSETS (HAO INCOME) D'IMMOBILISATIONS",
  821: 'PROCEEDS FROM DISPOSAL OF INTANGIBLE ASSETS',
  822: 'PROCEEDS FROM DISPOSAL OF TANGIBLE ASSETS',
  826: 'PROCEEDS FROM DISPOSAL OF FINANCIAL ASSETS',

  // ────────── 83 CHARGES OUTSIDE ORDINARY ACTIVITIES (HAO) ──────────
  83: 'EXTRAORDINARY / NON-ORDINARY ACTIVITY CHARGES (HAO EXPENSES)',
  831: 'RECOGNISED HAO CHARGES (EXTRAORDINARY EXPENSES)',
  834: 'LOSSES ON WRITE-OFF OF HAO RECEIVABLES',
  835: 'GIFTS AND DONATIONS MADE',
  836: 'DEBT WAIVERS AND WRITE-OFFS GRANTED TO THIRD PARTIES',
  839: 'HAO PROVISIONS CHARGED (EXTRAORDINARY RISK PROVISIONS)',

  // ────────── 84 INCOME OUTSIDE ORDINARY ACTIVITIES (HAO) ──────────
  84: 'EXTRAORDINARY / NON-ORDINARY ACTIVITY INCOME (HAO REVENUES)',
  841: 'RECOGNISED HAO INCOME (EXTRAORDINARY REVENUES)',
  845: 'GIFTS AND DONATIONS RECEIVED',
  846: 'DEBT WAIVERS RECEIVED FROM THIRD PARTIES',
  848: 'HAO CHARGE TRANSFERS',
  849: 'REVERSALS OF HAO RISK PROVISIONS',

  // ────────── 85 PROVISION CHARGES OUTSIDE ORDINARY ACTIVITIES (HAO) ──────────
  85: 'HAO DEPRECIATION, AMORTISATION AND PROVISION CHARGES (EXTRAORDINARY)',
  851: 'REGULATED PROVISION CHARGES (HAO)',
  852: 'ACCELERATED / EXTRAORDINARY DEPRECIATION CHARGES (HAO)',
  853: 'HAO IMPAIRMENT PROVISION CHARGES',
  854: 'HAO RISK AND CHARGE PROVISION CHARGES',
  858: 'OTHER HAO PROVISION CHARGES',

  // ────────── 86 REVERSAL OF PROVISIONS OUTSIDE ORDINARY ACTIVITIES (HAO) ──────────
  86: 'REVERSALS OF HAO PROVISIONS AND AMORTISATION (EXTRAORDINARY)',
  861: 'REVERSALS OF REGULATED PROVISIONS (HAO)',
  862: "REVERSALS OF EXTRAORDINARY DEPRECIATION (HAO) D'AMORTISSEMENTS",
  863: 'REVERSALS OF HAO IMPAIRMENT PROVISIONS',
  864: 'REVERSALS OF HAO RISK AND CHARGE PROVISIONS',
  865: "TRANSFER OF INVESTMENT GRANTS TO PROFIT (ANNUAL AMORTISATION) D'INVESTISSEMENT",
  868: 'OTHER HAO PROVISION REVERSALS',

  // ────────── 87 EMPLOYEE PROFIT-SHARING ──────────
  87: 'EMPLOYEE PROFIT-SHARING CHARGES',
  871: 'STATUTORY EMPLOYEE PROFIT-SHARING CHARGE',
  874: 'CONTRACTUAL EMPLOYEE PROFIT-SHARING CHARGE',
  878: 'OTHER EMPLOYEE PARTICIPATION CHARGES',

  // ────────── 88 BALANCING GRANTS ──────────
  88: "EQUIPMENT GRANTS'ÉQUILIBRE",
  881: 'BALANCING GRANT FROM THE STATE',
  884: 'BALANCING GRANT FROM PUBLIC AUTHORITIES',
  886: 'BALANCING GRANT FROM THE GROUP',
  888: 'BALANCING GRANT FROM OTHER SOURCES',

  // ────────── 89 INCOME TAXES ──────────
  89: 'INCOME TAX (CORPORATE TAX ON PROFIT)',
  891: "CURRENT YEAR CORPORATE INCOME TAX L'EXERCICE",
  8911: "Income tax on activities in the home State'État",
  8912: 'Income tax on activities in other UEMOA member states',
  8913: 'Income tax on activities outside the UEMOA region',
  892: "ADDITIONAL TAX ASSESSMENTS ON PRIOR YEAR RESULTS D'IMPÔTS SUR RÉSULTATS ANTÉRIEURS",
  895: 'MINIMUM FLAT-RATE TAX (IMF)',
  899: "TAX CREDITS AND CANCELLATIONS RELATING TO PRIOR YEAR TAXES D'IMPÔTS SUR RÉSULTATS ANTÉRIEURS",
  8991: 'Tax rebates and reductions on prior year taxes',
  8994: 'Tax annulments due to retroactive losses',
} as const satisfies Plan;

export type Class8AccountCode = keyof typeof class8Accounts;
