import type { Plan } from './types';

/**
 * SYSCOHADA — CLASS 2: Fixed / Non-Current Assets
 * (Class 2: Fixed / Non-Current Assets)
 *
 * Covers: deferred charges, intangible assets, land, buildings,
 * equipment, advances on fixed assets, investments, depreciation,
 * and impairment provisions.
 *
 * Source: Official SYSCOHADA Chart of Accounts PDF, pages 11–20.
 */
export const class2Accounts = {
  // ────────── 20 DEFERRED CHARGES ──────────
  20: 'DEFERRED CHARGES',
  201: "START-UP / FORMATION COSTS D'ÉTABLISSEMENT",
  2011: 'Incorporation costs',
  2012: 'Prospecting / survey costs',
  2013: 'Advertising and launch costs',
  2014: 'Pre-operating costs incurred before start of business',
  2015: 'Capital restructuring costs (mergers, demergers, conversions)',
  2016: "Stock exchange listing costs'entrée à la Bourse",
  2017: 'Restructuring costs',
  2018: "Miscellaneous formation costs'établissement",
  202: 'CHARGES TO BE SPREAD OVER SEVERAL ACCOUNTING PERIODS',
  2021: 'Deferred charges',
  2022: "Fixed asset acquisition costs'acquisition d'immobilisations",
  2026: "Bond issuance costs'émission des emprunts",
  2028: 'Charges to be spread (other)',
  206: 'BOND REDEMPTION PREMIUMS',
  2061: 'Redemption premiums',
  2062: 'Redemption premiums',
  2068: 'Redemption premiums',

  // ────────── 21 INTANGIBLE ASSETS ──────────
  21: 'INTANGIBLE ASSETS',
  211: 'RESEARCH AND DEVELOPMENT COSTS (CAPITALISED)',
  212: 'PATENTS, LICENCES, CONCESSIONS AND SIMILAR RIGHTS',
  213: 'SOFTWARE (COMPUTER PROGRAMS)',
  214: 'TRADEMARKS AND BRAND NAMES',
  215: 'GOODWILL (BUSINESS VALUE / FONDS DE COMMERCE)',
  216: 'LEASEHOLD RIGHTS (DROIT AU BAIL)',
  217: 'CREATIVE / ARTISTIC INVESTMENTS',
  218: 'OTHER INTANGIBLE RIGHTS AND VALUES',
  219: 'INTANGIBLE ASSETS UNDER CONSTRUCTION / DEVELOPMENT',
  2191: 'R&D in progress',
  2193: 'Software under development',
  2198: 'Other intangibles in progress',

  // ────────── 22 LAND ──────────
  22: 'LAND',
  221: 'AGRICULTURAL AND FORESTRY LAND',
  2211: "Agricultural operational land'exploitation agricole",
  2212: "Forestry operational land'exploitation forestière",
  2218: 'Other land',
  222: 'BARE / UNDEVELOPED LAND',
  2221: 'Building plots (land for development)',
  2228: 'Other undeveloped land',
  223: 'LAND WITH BUILDINGS',
  2231: 'Land for industrial and agricultural buildings',
  2232: 'Land for administrative and commercial buildings',
  2234: 'Land for other professional use buildings',
  2235: 'Land for non-professional use buildings',
  2238: 'Other land with buildings',
  224: 'LAND DEVELOPMENT WORKS',
  2241: "Tree and shrub planting works'arbres et d'arbustes",
  2248: 'Other land development works',
  225: 'MINERAL / QUARRY LAND (EXTRACTIVE SITES)',
  2251: 'Quarries',
  226: 'DEVELOPED / IMPROVED LAND',
  2261: 'Car park land',
  227: 'LAND HELD UNDER CONCESSION',
  228: 'OTHER LAND',
  2281: 'Land for rental property buildings',
  2285: 'Land for staff accommodation',
  2288: 'Other land',
  229: 'LAND IMPROVEMENTS UNDER CONSTRUCTION',
  2291: 'Agricultural/forestry land improvements in progress',
  2292: 'Bare land improvements in progress',
  2295: 'Mineral land improvements in progress',
  2298: 'Other land',

  // ────────── 23 BUILDINGS, TECHNICAL INSTALLATIONS AND FIXTURES ──────────
  23: 'BUILDINGS, TECHNICAL INSTALLATIONS AND FITTINGS',
  231: 'INDUSTRIAL, AGRICULTURAL, ADMINISTRATIVE AND COMMERCIAL BUILDINGS ON OWN LAND',
  2311: 'Industrial buildings (own land)',
  2312: 'Agricultural buildings (own land)',
  2313: 'Administrative and commercial buildings (own land)',
  2314: 'Staff accommodation buildings (own land)',
  2315: 'Rental investment property buildings (own land)',
  232: "INDUSTRIAL, AGRICULTURAL, ADMINISTRATIVE AND COMMERCIAL BUILDINGS ON THIRD-PARTY LAND D'AUTRUI",
  2321: 'Industrial buildings (third-party land)',
  2322: 'Agricultural buildings (third-party land)',
  2323: 'Administrative and commercial buildings (third-party land)',
  2324: 'Staff accommodation buildings (third-party land)',
  2325: 'Rental investment property buildings (third-party land)',
  233: "INFRASTRUCTURE WORKS D'INFRASTRUCTURE",
  2331: 'Roads and earthworks',
  2332: 'Railway infrastructure',
  2333: "Waterways'eau",
  2334: 'Dams and dikes',
  2335: "Airfield runways and taxiways'aérodrome",
  2338: 'Other',
  234: 'TECHNICAL INSTALLATIONS',
  2341: 'Specialised complex installations on own land',
  2342: "Specialised complex installations on third-party land'autrui",
  2343: 'Specific installations on own land',
  2344: "Specific installations on third-party land'autrui",
  235: 'OFFICE FIT-OUTS AND FITTINGS',
  2351: 'General office installations',
  2358: 'Other',
  237: 'INDUSTRIAL, AGRICULTURAL AND COMMERCIAL BUILDINGS HELD UNDER CONCESSION',
  238: 'OTHER INSTALLATIONS AND FITTINGS',
  239: 'BUILDINGS AND INSTALLATIONS UNDER CONSTRUCTION',

  // ────────── 24 EQUIPMENT AND MACHINERY ──────────
  24: 'EQUIPMENT AND MACHINERY',
  241: 'INDUSTRIAL AND COMMERCIAL MACHINERY AND TOOLS',
  2411: 'Industrial machinery',
  2412: 'Industrial tools',
  2413: 'Commercial equipment',
  2414: 'Commercial tools',
  242: 'AGRICULTURAL EQUIPMENT AND TOOLS',
  2421: 'Agricultural machinery',
  2422: 'Agricultural tools',
  243: "RETURNABLE AND INDIVIDUALLY IDENTIFIABLE PACKAGING EQUIPMENT D'EMBALLAGE RÉCUPÉRABLE ET IDENTIFIABLE",
  244: 'OFFICE EQUIPMENT AND FURNITURE',
  2441: 'Office equipment',
  2442: 'Computer hardware and IT equipment',
  2443: 'Office machines (printers, copiers, etc.)',
  2444: 'Office furniture',
  2446: 'Equipment and furniture in rental/investment buildings',
  2447: 'Equipment and furniture in staff accommodation',
  245: 'TRANSPORT EQUIPMENT AND VEHICLES',
  2451: 'Motor vehicles',
  2452: 'Railway rolling stock',
  2453: 'River and lagoon watercraft',
  2454: 'Sea-going vessels',
  2455: 'Aircraft',
  2456: 'Horse-drawn vehicles',
  2458: 'Other transport (bicycle, moped, motorcycle)',
  246: 'BIOLOGICAL ASSETS',
  2461: 'Draft animals / livestock (working animals)',
  2462: 'Breeding livestock',
  2463: 'Guard animals',
  2465: 'Perennial agricultural plantations',
  2468: 'Other',
  247: 'EQUIPMENT FITTINGS AND IMPROVEMENTS',
  248: 'OTHER EQUIPMENT',
  2481: "Collections and works of art'art",
  249: 'EQUIPMENT UNDER CONSTRUCTION',
  2491: 'Industrial and commercial equipment in progress',
  2492: 'Agricultural equipment in progress',
  2493: "Returnable packaging equipment in progress'emballage récupérable et identifiable",
  2494: 'Office equipment and furniture in progress',
  2495: 'Transport equipment in progress',
  2496: 'Biological assets in progress',
  2497: 'Equipment fittings in progress',
  2498: 'Other equipment in progress',

  // ────────── 25 ADVANCES AND PAYMENTS ON ACCOUNT ON FIXED ASSETS ──────────
  25: 'ADVANCES AND DEPOSITS PAID ON FIXED ASSETS (PREPAYMENTS TO SUPPLIERS OF NON-CURRENT ASSETS)',
  251: 'ADVANCES PAID ON INTANGIBLE ASSETS',
  252: 'ADVANCES PAID ON TANGIBLE ASSETS',

  // ────────── 26 EQUITY PARTICIPATIONS ──────────
  26: 'EQUITY INVESTMENTS (SHAREHOLDINGS)',
  261: 'EQUITY INVESTMENTS IN SUBSIDIARIES (EXCLUSIVE CONTROL)',
  262: 'EQUITY INVESTMENTS IN JOINTLY CONTROLLED ENTITIES',
  263: 'EQUITY INVESTMENTS IN ASSOCIATES (SIGNIFICANT INFLUENCE)',
  265: 'INTERESTS IN PROFESSIONAL ORGANISATIONS',
  266: "INTERESTS IN ECONOMIC INTEREST GROUPS (EIG / GIE) D'INTÉRÊT ÉCONOMIQUE (G.I.E.)",
  268: 'OTHER EQUITY INVESTMENT SECURITIES',

  // ────────── 27 OTHER FINANCIAL ASSETS ──────────
  27: 'OTHER LONG-TERM FINANCIAL ASSETS',
  271: 'LONG-TERM LOANS AND NON-TRADE RECEIVABLES',
  2711: 'Participating loans granted',
  2712: 'Loans to shareholders/partners',
  2713: 'Business purchase notes receivable',
  2714: 'Securities lent to third parties',
  272: 'LOANS TO EMPLOYEES',
  2721: 'Housing loans to employees',
  2722: "Equipment and installation loans to employees'installation",
  2728: "Other loans to employees (education, etc.)'études…)",
  273: "LONG-TERM RECEIVABLES FROM THE STATE L'ÉTAT",
  2731: 'Guarantee retentions',
  2733: 'Regulated fund receivable',
  2738: 'Other',
  274: 'LONG-TERM INVESTMENT SECURITIES',
  2741: "Portfolio investment securities (TIAP)'activité de portefeuille (T.I.A.P.)",
  2742: 'Participating securities (non-voting bonds)',
  2743: "Investment certificates'investissement",
  2744: 'Mutual fund units (FCP)',
  2748: 'Other long-term investment securities',
  275: 'DEPOSITS AND SURETIES PAID (LONG-TERM)',
  2751: "Rental deposits paid'avance",
  2752: "Electricity deposits paid'électricité",
  2753: "Water deposits paid'eau",
  2754: 'Gas deposits paid',
  2755: 'Telephone and telecoms deposits paid',
  2756: 'Public contract sureties paid',
  2757: 'Other sureties paid',
  2758: 'Other deposits and sureties paid',
  276: 'ACCRUED INTEREST',
  2761: 'Accrued interest on non-trade loans',
  2762: 'Accrued interest on employee loans',
  2763: "Accrued interest on State receivables'Etat",
  2764: 'Accrued interest on long-term securities',
  2765: 'Accrued interest on deposits paid',
  2767: 'Accrued interest on participation-related receivables',
  2768: 'Accrued interest on other long-term financial assets',
  277: 'RECEIVABLES RELATED TO EQUITY INVESTMENTS AND ADVANCES TO GIE',
  2771: 'Intra-group participation receivables',
  2772: 'Non-group participation receivables',
  2773: 'Receivables from joint venture entities',
  2774: "Advances to Economic Interest Groups'intérêt économique (G.I.E.)",
  278: 'MISCELLANEOUS LONG-TERM FINANCIAL ASSETS',
  2781: 'Miscellaneous intra-group receivables',
  2782: 'Miscellaneous non-group receivables',
  2785: 'Gold and precious metals held as financial assets',

  // ────────── 28 DEPRECIATION ──────────
  28: 'DEPRECIATION',
  281: 'ACCUMULATED DEPRECIATION',
  2811: 'Depreciation',
  2812: 'Depreciation',
  2813: 'Depreciation',
  2814: 'Depreciation',
  2815: 'Amortisation',
  2816: 'Amortisation',
  2817: 'Depreciation',
  2818: 'Depreciation',
  282: 'ACCUMULATED DEPRECIATION',
  2821: 'Depreciation',
  2824: 'Depreciation',
  2825: 'Depreciation',
  283: 'ACCUMULATED DEPRECIATION',
  2831: 'Depreciation',
  2832: "Depreciation'autrui",
  2833: "Depreciation'infrastructure",
  2834: 'Depreciation',
  2835: 'Depreciation',
  2837: 'Depreciation',
  2838: 'Depreciation',
  284: 'ACCUMULATED DEPRECIATION',
  2841: 'Depreciation',
  2842: 'Depreciation',
  2843: "Depreciation'emballage récupérable et identifiable",
  2844: 'Depreciation',
  2845: 'Depreciation',
  2846: 'Depreciation',
  2847: 'Depreciation',
  2848: 'Depreciation',

  // ────────── 29 IMPAIRMENT OF FIXED ASSETS ──────────
  29: 'IMPAIRMENT PROVISIONS ON FIXED ASSETS (CONTRA ACCOUNT)',
  291: 'IMPAIRMENT PROVISIONS',
  2912: 'Impairment',
  2913: 'Impairment',
  2914: 'Impairment',
  2915: 'Impairment',
  2916: 'Impairment',
  2917: 'Impairment',
  2918: 'Impairment',
  2919: 'Impairment',
  292: 'IMPAIRMENT PROVISIONS',
  2921: 'Impairment',
  2922: 'Impairment',
  2923: 'Impairment',
  2924: 'Impairment',
  2925: 'Impairment',
  2926: 'Impairment',
  2927: 'Impairment',
  2928: 'Impairment',
  2929: 'Impairment',
  293: 'IMPAIRMENT PROVISIONS',
  2931: 'Impairment',
  2932: "Impairment'autrui",
  2933: "Impairment'infrastructures",
  2934: 'Impairment',
  2935: 'Impairment',
  2937: 'Impairment',
  2938: 'Impairment',
  2939: 'Impairment',
  294: 'IMPAIRMENT PROVISIONS',
  2941: 'Impairment',
  2942: 'Impairment',
  2943: "Impairment'emballage récupérable et identifiable",
  2944: 'Impairment',
  2945: 'Impairment',
  2946: 'Impairment',
  2947: 'Impairment',
  2948: 'Impairment',
  2949: 'Impairment',
  295: 'IMPAIRMENT PROVISIONS',
  2951: 'Impairment',
  2952: 'Impairment',
  296: 'IMPAIRMENT PROVISIONS',
  2961: 'Impairment',
  2962: 'Impairment',
  2963: 'Impairment',
  2965: 'Impairment',
  2966: 'Impairment',
  2968: 'Impairment',
  297: 'IMPAIRMENT PROVISIONS',
  2971: 'Impairment',
  2972: 'Impairment',
  2973: "Impairment'Etat",
  2974: 'Impairment',
  2975: 'Impairment',
  2977: 'Impairment',
  2978: 'Impairment',
} as const satisfies Plan;

export type Class2AccountCode = keyof typeof class2Accounts;
