/**
 * SYSCOHADA — CLASS 4: Third-Party Accounts
 * (Class 4: Third-Party Accounts — Receivables & Payables)
 *
 * Covers: suppliers, customers, employees, social organisations,
 * State/public authorities, international organisations, shareholders,
 * miscellaneous debtors/creditors, HAO receivables/payables,
 * and impairment provisions.
 *
 * Source: Official SYSCOHADA Chart of Accounts PDF, pages 23–30.
 */
import type { Plan } from './types';

export const class4Accounts = {
  // ────────── 40 SUPPLIERS AND RELATED ACCOUNTS ──────────
  40: 'SUPPLIERS AND RELATED ACCOUNTS',
  401: 'SUPPLIERS',
  4011: 'Trade suppliers',
  4012: 'Intra-group suppliers',
  4013: 'Subcontractor suppliers',
  4017: 'Supplier',
  402: 'SUPPLIERS',
  4021: 'Trade supplier bills payable',
  4022: 'Intra-group supplier bills payable',
  4023: 'Subcontractor bills payable',
  408: 'SUPPLIERS',
  4081: 'Accrued trade supplier payables',
  4082: 'Accrued intra-group supplier payables',
  4083: 'Accrued subcontractor payables',
  4086: 'Accrued interest on supplier payables',
  409: 'SUPPLIERS',
  4091: 'Advances and deposits paid to suppliers',
  4092: 'Advances paid to group suppliers',
  4093: 'Advances paid to subcontractors',
  4094: 'Claims on suppliers for packaging and equipment to be returned',
  4098: 'Rebates, discounts and other credits to be received from suppliers',

  // ────────── 41 CUSTOMERS AND RELATED ACCOUNTS ──────────
  41: 'CUSTOMERS AND RELATED ACCOUNTS',
  411: 'TRADE RECEIVABLES',
  4111: 'Customers',
  4112: 'Intra-group customers',
  4114: 'Public-sector customers (State and local authorities)',
  4115: 'International organisation customers',
  4117: 'Customer',
  4118: 'Customers',
  412: 'CUSTOMERS',
  4121: 'Trade customer bills receivable',
  4122: 'Intra-group customer bills receivable',
  4124: 'Public authority bills receivable',
  4125: 'International organisation bills receivable',
  414: "RECEIVABLES FROM ASSET DISPOSALS D'IMMOBILISATIONS",
  4141: 'Asset disposal receivables',
  4142: 'Asset disposal receivables',
  415: 'CUSTOMER BILLS DISCOUNTED BUT NOT YET DUE',
  416: 'DISPUTED OR DOUBTFUL CUSTOMER RECEIVABLES',
  4161: 'Disputed customer receivables',
  4162: 'Doubtful / impaired customer receivables',
  418: 'CUSTOMERS',
  4181: 'Accrued customer revenue',
  4186: 'Accrued interest on customer receivables',
  419: 'CUSTOMERS',
  4191: 'Advances and deposits received from customers',
  4192: 'Advances received from group customers',
  4194: 'Liabilities to customers for consigned packaging and equipment',
  4198: 'Rebates and credits to be granted to customers',

  // ────────── 42 PERSONNEL ──────────
  42: 'PERSONNEL',
  421: 'EMPLOYEE ADVANCES AND SALARY ADVANCES',
  4211: 'Advances to employees',
  4212: 'Salary advances (partial payments)',
  4213: 'Expenses paid and goods supplied to employees',
  422: 'SALARIES AND WAGES PAYABLE',
  423: 'WAGE GARNISHMENTS AND ATTACHMENTS',
  4231: 'Wage oppositions / freezes',
  4232: 'Wage garnishments',
  4233: 'Third-party holder notices on wages',
  424: 'EMPLOYEE WELFARE BENEFITS (COMPANY-MANAGED)',
  4241: 'Company medical assistance',
  4242: 'Family allowances',
  4245: "Company-affiliated social organisations'entreprise",
  4248: 'Other internal employee welfare programs',
  425: 'EMPLOYEE REPRESENTATIVES (WORKS COUNCIL, UNIONS)',
  4251: 'Employee delegates',
  4252: "Trade unions and works councils'entreprise, d'Établissement",
  4258: 'Other employee representatives',
  426: 'EMPLOYEE PROFIT-SHARING PAYABLE',
  427: 'EMPLOYEE DEPOSITS HELD',
  428: 'EMPLOYEE-RELATED ACCRUED LIABILITIES AND RECEIVABLES',
  4281: 'Accrued holiday/leave pay liability',
  4286: 'Other accrued employee charges',
  4287: 'Accrued income',

  // ────────── 43 SOCIAL SECURITY ORGANISATIONS ──────────
  43: 'SOCIAL SECURITY AND SOCIAL ORGANISATIONS',
  431: 'SOCIAL SECURITY CONTRIBUTIONS PAYABLE',
  4311: 'Family benefit contributions',
  4312: 'Workplace accident contributions',
  4313: 'Mandatory pension fund contributions',
  4314: 'Optional pension fund contributions',
  4318: 'Other social security contributions',
  432: 'SUPPLEMENTARY PENSION FUND CONTRIBUTIONS',
  433: 'OTHER SOCIAL ORGANISATIONS',
  4331: 'Mutual insurance fund contributions',
  438: 'ACCRUED SOCIAL CHARGES AND RECEIVABLES',
  4381: 'Social charges on accrued bonuses',
  4382: 'Social charges on accrued leave pay',
  4386: 'Other accrued social charges',
  4387: 'Accrued income',

  // ────────── 44 STATE AND PUBLIC AUTHORITIES ──────────
  44: 'STATE AND PUBLIC AUTHORITIES',
  441: 'CORPORATE INCOME TAX PAYABLE / RECOVERABLE',
  442: 'STATE',
  4421: "State taxes and duties'Etat",
  4422: 'Local authority taxes and duties',
  4423: 'Taxes recoverable on bondholders',
  4424: 'Taxes recoverable on shareholders',
  4426: 'Customs duties',
  4428: 'Other taxes and duties',
  443: 'OUTPUT VAT (BILLED/CHARGED TO CUSTOMERS)',
  4431: 'Output VAT on sales of goods',
  4432: 'Output VAT on services rendered',
  4433: 'Output VAT on construction works',
  4334: 'Output VAT on self-supply',
  4335: 'Output VAT on accrued revenue (invoices to be issued)',
  444: 'VAT PAYABLE OR VAT CREDIT BALANCE',
  4441: 'VAT payable to the State (net VAT liability)',
  4449: 'VAT credit to be carried forward (recoverable)',
  445: 'INPUT VAT RECOVERABLE',
  4451: 'Input VAT on fixed asset purchases',
  4452: 'Input VAT on stock and supply purchases',
  4453: 'Input VAT on transport services',
  4454: 'Input VAT on external services and other charges',
  4455: 'Input VAT on uninvoiced purchases',
  4456: "VAT transferred from other companies'autres entreprises",
  446: "STATE D'AFFAIRES",
  447: 'STATE',
  4471: 'General income tax withheld',
  4472: 'Payroll taxes withheld',
  4473: 'National contribution withheld',
  4474: 'National solidarity contribution withheld',
  4478: 'Other withholding taxes and contributions',
  448: 'STATE',
  4486: 'Accrued tax charges',
  4487: 'Accrued income',
  449: 'STATE',
  4491: 'State',
  4492: 'Tax advances and prepayments made',
  4493: 'State endowment funds receivable',
  4494: "Equipment grants receivable from the State'équipement à recevoir",
  4495: "Operating grants receivable from the State'exploitation à recevoir",
  4496: "Balancing grants receivable from the State'équilibre à recevoir",
  4499: 'State',

  // ────────── 45 INTERNATIONAL ORGANISATIONS ──────────
  45: 'INTERNATIONAL ORGANISATIONS',
  451: 'TRANSACTIONS WITH AFRICAN ORGANISATIONS',
  452: 'TRANSACTIONS WITH OTHER INTERNATIONAL ORGANISATIONS',
  458: 'INTERNATIONAL ORGANISATIONS',
  4581: 'Endowment funds receivable from international organisations',
  4582: 'Grants receivable from international organisations',

  // ────────── 46 PARTNERS AND GROUP ──────────
  46: 'SHAREHOLDERS, PARTNERS AND GROUP COMPANIES',
  461: 'SHAREHOLDERS',
  4611: 'Shareholders',
  4612: 'Shareholders',
  4613: 'Shareholders',
  4614: 'Partners',
  4615: 'Shareholders',
  4616: 'Shareholders',
  4617: 'Defaulting shareholders',
  4618: 'Partners',
  4619: 'Shareholders',
  462: 'SHAREHOLDERS',
  4621: 'Partner current account',
  4626: 'Accrued interest on partner current accounts',
  463: 'PARTNERS',
  465: 'DIVIDENDS PAYABLE TO SHAREHOLDERS',
  466: 'GROUP COMPANIES',
  467: 'SHAREHOLDERS',

  // ────────── 47 SUNDRY DEBTORS AND CREDITORS ──────────
  47: 'MISCELLANEOUS DEBTORS AND CREDITORS',
  471: "SUSPENSE ACCOUNTS (TEMPORARY HOLDING ACCOUNTS) D'ATTENTE",
  4711: 'Miscellaneous debtors',
  4712: 'Miscellaneous creditors',
  472: 'REMAINING PAYMENTS DUE ON PARTIALLY PAID-UP SECURITIES',
  4726: 'Unpaid calls on equity investments',
  4727: 'Unpaid calls on long-term securities',
  4728: 'Unpaid calls on short-term investment securities',
  474: 'PERIODIC ALLOCATION OF INCOME AND EXPENSES (ACCRUALS AND DEFERRALS)',
  4746: 'Periodic expense allocation',
  4747: 'Periodic income allocation',
  475: 'RECEIVABLES ON WORK NOT YET BILLABLE (CONTRACT WORK IN PROGRESS)',
  476: "PREPAID EXPENSES (DEFERRED CHARGES) D'AVANCE",
  477: "DEFERRED INCOME (DEFERRED REVENUE) D'AVANCE",
  478: 'TRANSLATION DIFFERENCES',
  4781: 'Decrease in foreign-currency receivables due to exchange rate movement',
  4782: 'Increase in foreign-currency payables due to exchange rate movement',
  4788: 'Translation differences offset by hedging',
  479: 'TRANSLATION DIFFERENCES',
  4791: 'Increase in foreign-currency receivables due to exchange rate movement',
  4792: 'Decrease in foreign-currency payables due to exchange rate movement',
  4798: 'Translation gains offset by hedging',

  // ────────── 48 RECEIVABLES AND PAYABLES OUTSIDE ORDINARY ACTIVITIES (HAO) ──────────
  48: 'NON-ORDINARY ACTIVITY RECEIVABLES AND PAYABLES (CAPITAL ACCOUNT ITEMS)',
  481: "SUPPLIERS OF FIXED ASSETS (CAPITAL EXPENDITURE PAYABLES) D'INVESTISSEMENTS",
  4811: 'Payables for intangible assets purchased',
  4812: 'Payables for tangible assets purchased',
  4817: 'Guarantee retentions',
  4818: 'Uninvoiced capital expenditure payables',
  482: "CAPITAL EXPENDITURE SUPPLIERS D'INVESTISSEMENTS, EFFETS À PAYER",
  483: 'PAYABLES ON ACQUISITION OF INVESTMENT SECURITIES',
  484: 'OTHER NON-ORDINARY ACTIVITY PAYABLES',
  485: "RECEIVABLES FROM FIXED ASSET DISPOSALS D'IMMOBILISATIONS",
  4851: 'Asset disposal receivables',
  4852: 'Asset disposal receivables',
  4857: 'Guarantee retentions',
  4858: 'Asset disposal receivables',
  486: 'RECEIVABLES FROM DISPOSAL OF INVESTMENT SECURITIES',
  488: 'OTHER NON-ORDINARY ACTIVITY RECEIVABLES',

  // ────────── 49 IMPAIRMENT AND RISK PROVISIONS (THIRD PARTY) ──────────
  49: 'IMPAIRMENT PROVISIONS AND PROVISIONED RISKS ON THIRD-PARTY ACCOUNTS (TIERS)',
  490: 'IMPAIRMENT ON SUPPLIER ACCOUNTS',
  491: 'IMPAIRMENT ON CUSTOMER RECEIVABLES',
  4911: 'Impairment',
  4912: 'Impairment',
  492: 'IMPAIRMENT ON EMPLOYEE RECEIVABLES',
  493: 'IMPAIRMENT ON SOCIAL ORGANISATION RECEIVABLES',
  494: 'IMPAIRMENT ON STATE AND PUBLIC AUTHORITY RECEIVABLES',
  495: 'IMPAIRMENT ON INTERNATIONAL ORGANISATION RECEIVABLES',
  496: 'IMPAIRMENT ON SHAREHOLDER AND GROUP RECEIVABLES',
  4962: 'Impairment on partner current accounts',
  4963: 'Impairment on joint venture transactions',
  4966: 'Impairment on group current accounts',
  497: 'IMPAIRMENT ON MISCELLANEOUS DEBTOR ACCOUNTS',
  498: 'IMPAIRMENT ON NON-ORDINARY ACTIVITY RECEIVABLES',
  4981: "Impairment on asset disposal receivables'immobilisations",
  4982: 'Impairment on investment security disposal receivables',
  4983: 'Impairment on other non-ordinary receivables',
  499: 'SHORT-TERM PROVISIONS FOR RISKS',
  4991: "Short-term provisions for operating risks'exploitation",
  4998: 'Short-term provisions for non-ordinary activity risks',
} as const satisfies Plan;

export type Class4AccountCode = keyof typeof class4Accounts;
