import type { Plan } from './types';

/**
 * SYSCOHADA — CLASS 1: Durable Funding Resources
 * (Class 1: Durable Funding Resources)
 *
 * Covers: equity (capital, reserves, retained earnings), investment grants,
 * regulated provisions, borrowings, lease liabilities, participation debts,
 * and financial provisions for risks and charges.
 *
 * Source: Official SYSCOHADA Chart of Accounts PDF, pages 7–11.
 */
export const class1Accounts = {
  // ────────── 10 CAPITAL ──────────
  10: 'CAPITAL',
  101: 'SHARE CAPITAL',
  1011: 'Subscribed capital, not yet called up',
  1012: 'Subscribed capital, called up but not yet paid in',
  1013: 'Subscribed capital, called up, paid in, not yet redeemed',
  1014: 'Subscribed capital, called up, paid in and redeemed',
  1018: 'Subscribed capital subject to special conditions',
  102: 'ENDOWMENT CAPITAL',
  1021: 'Initial endowment',
  1022: 'Supplementary endowments',
  1028: 'Other endowments',
  103: 'SOLE-TRADER PERSONAL CAPITAL',
  104: "OWNER L'EXPLOITANT",
  1041: 'Temporary contributions by the owner',
  1042: 'Current operating transactions with the owner',
  1043: 'Owner',
  1047: "Owner withdrawals of goods for personal consumption'autoconsommation",
  1048: 'Other owner withdrawals',
  105: 'SHARE PREMIUMS',
  1051: "Share issue premium'émission",
  1052: "Contribution premium'apport",
  1053: 'Merger premium',
  1054: 'Conversion premium',
  1058: 'Other equity-related premiums',
  106: 'REVALUATION SURPLUS',
  1061: 'Legal revaluation surplus (mandatory revaluation)',
  1062: 'Free revaluation surplus (voluntary revaluation)',
  109: 'SHAREHOLDERS',

  // ────────── 11 RESERVES ──────────
  11: 'RESERVES',
  111: 'LEGAL RESERVE',
  112: 'STATUTORY OR CONTRACTUAL RESERVES',
  113: 'REGULATED RESERVES',
  1131: 'Reserve for net long-term capital gains',
  1133: "Reserve arising from investment grants received'octroi de subventions d'investissement",
  1138: 'Other regulated reserves',
  118: 'OTHER RESERVES',
  1181: 'Optional (discretionary) reserves',
  1188: 'Miscellaneous reserves',

  // ────────── 12 RETAINED EARNINGS ──────────
  12: 'RETAINED EARNINGS',
  121: 'RETAINED EARNINGS (CREDIT BALANCE)',
  129: 'ACCUMULATED LOSSES (DEBIT BALANCE)',
  1291: 'Net loss carried forward',
  1292: 'Loss',

  // ────────── 13 NET INCOME / LOSS ──────────
  13: "NET INCOME/LOSS FOR THE PERIOD L'EXERCICE",
  130: "PROFIT/LOSS PENDING APPROPRIATION D'AFFECTATION",
  1301: "Profit pending appropriation'affectation : Bénéfice",
  1309: "Loss pending appropriation'affectation : Perte",
  131: 'NET PROFIT FOR THE PERIOD',
  132: 'GROSS MARGIN',
  1321: 'Gross margin on merchandise',
  1322: 'Gross margin on raw materials',
  133: 'VALUE ADDED',
  134: "GROSS OPERATING SURPLUS (EBITDA EQUIVALENT) D'EXPLOITATION (E.B.E.)",
  135: "OPERATING RESULT D'EXPLOITATION (R.E.)",
  136: 'FINANCIAL RESULT',
  137: 'RESULT FROM ORDINARY ACTIVITIES (OPERATING + FINANCIAL)',
  138: 'RESULT FROM EXTRAORDINARY/NON-ORDINARY ACTIVITIES (HAO)',
  139: 'NET LOSS FOR THE PERIOD',

  // ────────── 14 INVESTMENT GRANTS ──────────
  14: "EQUIPMENT GRANTS'INVESTISSEMENT",
  141: "EQUIPMENT GRANTS'ÉQUIPEMENT A",
  1411: 'State',
  1412: 'Regions',
  1413: 'Departments',
  1414: 'Investment grant from municipalities and decentralised public bodies',
  1415: 'Investment grant from state-owned or mixed enterprises',
  1416: 'Investment grant from private companies and organisations',
  1417: 'Investment grant from international organisations',
  1418: 'Other',
  142: "EQUIPMENT GRANTS'ÉQUIPEMENT B",
  148: "OTHER INVESTMENT GRANTS'INVESTISSEMENT",

  // ────────── 15 REGULATED PROVISIONS AND EQUIVALENT FUNDS ──────────
  15: 'REGULATED PROVISIONS AND EQUIVALENT FUNDS',
  151: 'ACCELERATED (TAX-DRIVEN) DEPRECIATION PROVISIONS',
  152: 'CAPITAL GAINS TO BE REINVESTED',
  153: 'REGULATED FUNDS',
  1531: 'National regulated fund',
  1532: 'Budget levy provision',
  154: 'SPECIAL REVALUATION PROVISION (FISCAL NEUTRALITY PROVISION)',
  155: 'REGULATED PROVISIONS RELATING TO FIXED ASSETS (E.G. MINING/OIL FIELD RECONSTITUTION)',
  1551: 'Provision for reconstitution of mining and oil fields',
  156: 'REGULATED PROVISIONS RELATING TO INVENTORIES',
  1561: 'Price increase provision (stock)',
  1562: 'Market price fluctuation provision (stock)',
  157: 'INVESTMENT PROVISIONS',
  158: 'OTHER REGULATED PROVISIONS AND FUNDS',

  // ────────── 16 BORROWINGS AND SIMILAR LIABILITIES ──────────
  16: 'BORROWINGS AND SIMILAR LIABILITIES',
  161: 'BOND LOANS',
  1611: 'Ordinary bond loans',
  1612: 'Convertible bond loans',
  1618: 'Other bond loans',
  162: 'LOANS AND DEBTS FROM CREDIT INSTITUTIONS (BANKS)',
  163: "ADVANCES RECEIVED FROM THE STATE L'ÉTAT",
  164: 'ADVANCES RECEIVED AND BLOCKED CURRENT ACCOUNTS',
  165: 'DEPOSITS AND SURETIES RECEIVED',
  1651: 'Deposits',
  1652: 'Sureties (bonds) received',
  166: 'ACCRUED INTEREST',
  1661: 'on bond loans',
  1662: 'on bank loans',
  1663: "on State advances'État",
  1664: 'on blocked advances and current accounts',
  1665: 'on deposits and sureties received',
  1667: 'on advances with special conditions',
  1668: 'on other borrowings and debts',
  167: 'ADVANCES SUBJECT TO SPECIAL CONDITIONS (CONDITIONAL GRANTS)',
  1671: 'Advances blocked pending capital increase',
  1672: "Conditional advances from the State'État",
  1673: 'Conditional advances from other African organisations',
  1674: 'Conditional advances from international organisations',
  1676: 'Concession rights payable in kind',
  168: 'OTHER BORROWINGS AND DEBTS',
  1681: 'Capitalised life annuities',
  1682: 'Business purchase notes payable',
  1683: 'Debts arising from borrowed securities',
  1684: 'Concessionaire',
  1685: 'Participating loans',
  1686: 'Employee profit-sharing liability',

  // ────────── 17 LEASE LIABILITIES AND SIMILAR CONTRACTS ──────────
  17: 'FINANCE LEASE LIABILITIES AND SIMILAR CONTRACTS',
  172: 'FINANCE LEASE LIABILITIES',
  173: 'FINANCE LEASE LIABILITIES',
  176: 'ACCRUED INTEREST',
  1762: 'on real estate finance leases',
  1763: 'on movable asset finance leases',
  1768: "on other lease contracts'autres contrats",
  178: "FINANCE LEASE LIABILITIES D'AUTRES CONTRATS",

  // ────────── 18 DEBTS RELATED TO EQUITY PARTICIPATIONS ──────────
  18: 'DEBTS RELATED TO EQUITY INVESTMENTS AND INTER-BRANCH LIAISON ACCOUNTS',
  181: 'DEBTS RELATED TO EQUITY PARTICIPATIONS',
  1811: 'Intra-group participation debts',
  1812: 'Non-group participation debts',
  182: 'DEBTS RELATED TO JOINT VENTURES (SOCIÉTÉS EN PARTICIPATION)',
  183: 'ACCRUED INTEREST ON PARTICIPATION-RELATED DEBTS',
  184: 'BLOCKED PERMANENT ACCOUNTS OF BRANCHES AND SUBSIDIARIES',
  185: 'NON-BLOCKED PERMANENT ACCOUNTS OF BRANCHES AND SUBSIDIARIES',
  186: 'INTER-BRANCH LIAISON ACCOUNTS',
  187: 'INTER-BRANCH LIAISON ACCOUNTS',
  188: 'LIAISON ACCOUNTS FOR JOINT VENTURE ENTITIES',

  // ────────── 19 FINANCIAL PROVISIONS FOR RISKS AND CHARGES ──────────
  19: 'FINANCIAL PROVISIONS FOR RISKS AND CHARGES',
  191: 'PROVISIONS FOR LITIGATION AND LEGAL DISPUTES',
  192: 'PROVISIONS FOR WARRANTIES GIVEN TO CUSTOMERS',
  193: 'PROVISIONS FOR LOSSES ON LONG-TERM CONTRACTS',
  194: 'PROVISIONS FOR FOREIGN EXCHANGE LOSSES',
  195: 'PROVISIONS FOR TAXES',
  196: 'PROVISIONS FOR PENSIONS AND SIMILAR POST-EMPLOYMENT OBLIGATIONS',
  197: 'PROVISIONS FOR CHARGES TO BE SPREAD OVER SEVERAL ACCOUNTING PERIODS',
  1971: 'Provisions for major repairs and overhauls',
  198: 'OTHER FINANCIAL PROVISIONS FOR RISKS AND CHARGES',
  1981: 'Provisions for fines and penalties',
  1982: 'Provisions for asset renewal (concession companies)',
  1983: 'Self-insurance provisions',
  1988: 'Other miscellaneous financial provisions for risks and charges',
} as const satisfies Plan;

export type Class1AccountCode = keyof typeof class1Accounts;
