/**
 * SYSCOHADA — CLASS 6: Ordinary Activity Expense Accounts
 * (Class 6: Ordinary Activity Expense Accounts)
 *
 * Source: Official SYSCOHADA Chart of Accounts PDF, pages 33–40.
 */
import type { Plan } from './types';

export const class6Accounts = {
  // ────────── 60 PURCHASES AND INVENTORY MOVEMENTS ──────────
  60: 'PURCHASES AND INVENTORY MOVEMENTS',
  601: 'PURCHASES OF MERCHANDISE FOR RESALE',
  6011: 'within the Region',
  6012: 'outside the Region',
  6013: 'to group companies within the Region',
  6014: 'to group companies outside the Region',
  6019: 'Purchase rebates and discounts on merchandise (unallocated)',
  602: 'PURCHASES OF RAW MATERIALS AND RELATED SUPPLIES',
  6021: 'within the Region',
  6022: 'outside the Region',
  6023: 'to group companies within the Region',
  6024: 'to group companies outside the Region',
  6029: 'Purchase rebates and discounts on raw materials (unallocated)',
  603: 'CHANGE IN INVENTORIES OF PURCHASED GOODS (MERCHANDISE AND RAW MATERIALS)',
  6031: 'Change in merchandise inventory',
  6032: 'Change in raw material inventory',
  6033: "Change in other supply inventory'autres approvisionnements",
  604: 'PURCHASES OF CONSUMABLE MATERIALS AND SUPPLIES (HELD IN STOCK)',
  6041: 'Consumable materials purchased',
  6042: 'Fuel and combustible materials purchased',
  6043: "Cleaning and maintenance products purchased'entretien",
  6044: "Workshop and factory supplies purchased'atelier et d'usine",
  6046: 'Store/warehouse supplies purchased',
  6047: 'Office supplies purchased',
  6049: 'Purchase rebates on consumables (unallocated)',
  605: 'OTHER PURCHASES (NON-STOCK ITEMS AND SERVICES)',
  6051: 'Non-stock supplies',
  6052: 'Non-stock supplies',
  6053: 'Non-stock supplies',
  6054: "Non-stock maintenance supplies'entretien non stockables",
  6055: 'Non-stock office supplies',
  6056: 'Small equipment and tools purchased (expensed)',
  6057: "Purchases of studies and consulting services'études et prestations de services",
  6058: 'Purchases of works, materials and equipment (expensed)',
  6059: 'Purchase rebates on other purchases (unallocated)',
  608: "PURCHASES OF PACKAGING MATERIALS D'EMBALLAGES",
  6081: 'Non-returnable packaging purchased',
  6082: 'Returnable non-identifiable packaging purchased',
  6083: 'Mixed-use packaging purchased',
  6089: 'Purchase rebates on packaging (unallocated)',

  // ────────── 61 TRANSPORT EXPENSES ──────────
  61: 'TRANSPORT EXPENSES',
  611: 'INBOUND FREIGHT AND TRANSPORT ON PURCHASES',
  612: 'OUTBOUND FREIGHT AND TRANSPORT ON SALES',
  613: 'TRANSPORT ON BEHALF OF THIRD PARTIES',
  614: 'EMPLOYEE TRANSPORT AND COMMUTING EXPENSES',
  616: 'MAIL AND PARCEL DELIVERY EXPENSES',
  618: 'OTHER TRANSPORT EXPENSES',
  6181: 'Business travel and travel expenses',
  6182: 'Transfers between branches or construction sites',
  6183: 'Administrative transport expenses',

  // ────────── 62 EXTERNAL SERVICES A ──────────
  62: 'EXTERNAL SERVICES A',
  621: 'GENERAL SUBCONTRACTING EXPENSES',
  622: 'RENT AND OCCUPANCY CHARGES',
  6221: 'Land rental expenses',
  6222: 'Building and premises rental expenses',
  6223: 'Equipment and tool rental expenses',
  6224: 'Losses on packaging (unreturned packaging cost)',
  6225: "Packaging rental charges'emballages",
  6228: 'Miscellaneous rental and occupancy charges',
  623: 'FINANCE LEASE RENTALS AND SIMILAR CONTRACT PAYMENTS',
  6232: 'Real estate finance lease payments',
  6233: 'Movable asset finance lease payments',
  6235: 'Other similar contract payments',
  624: 'MAINTENANCE, REPAIRS AND UPKEEP EXPENSES',
  6241: 'Real estate maintenance and repairs',
  6242: 'Movable asset maintenance and repairs',
  6243: 'Maintenance contracts and services',
  6248: 'Other maintenance and repair costs',
  625: "INSURANCE PREMIUMS D'ASSURANCE",
  6251: 'Multi-risk (comprehensive) insurance premiums',
  6252: 'Vehicle insurance premiums',
  6253: "Business risk insurance premiums'exploitation",
  6254: 'Product liability insurance premiums',
  6255: 'Trade credit / bad debt insurance premiums',
  6256: 'Inbound transport insurance premiums',
  6257: 'Outbound transport insurance premiums',
  6258: "Other insurance premiums'assurances",
  626: 'STUDIES, RESEARCH AND DOCUMENTATION EXPENSES',
  6261: 'Research and feasibility study costs',
  6265: 'General documentation and library costs',
  6266: 'Technical documentation costs',
  627: 'ADVERTISING, PUBLICATIONS AND PUBLIC RELATIONS',
  6271: 'Advertising placements and insertions',
  6272: 'Catalogues and promotional printed materials',
  6273: 'Product samples',
  6274: 'Trade fairs and exhibitions',
  6275: 'Publications expenses',
  6276: 'Client gifts',
  6277: 'Conference, seminar and symposium costs',
  6278: 'Other advertising and PR expenses',
  628: 'TELECOMMUNICATIONS EXPENSES',
  6281: 'Telephone expenses',
  6282: 'Telex expenses',
  6283: 'Fax expenses',
  6288: 'Other telecommunications expenses',

  // ────────── 63 EXTERNAL SERVICES B ──────────
  63: 'EXTERNAL SERVICES B',
  631: 'BANK CHARGES AND FEES',
  6311: 'Securities transaction fees (buy, sell, custody)',
  6312: 'Bill of exchange handling charges',
  6313: 'Safe deposit box rental',
  6315: 'Credit card commission charges',
  6316: "Bond issuance fees'émission d'emprunts",
  6318: 'Other bank charges',
  632: "FEES PAID TO INTERMEDIARIES AND ADVISORS D'INTERMÉDIAIRES ET DE CONSEILS",
  6321: 'Commission and brokerage on purchases',
  6322: 'Commission and brokerage on sales',
  6323: 'Freight forwarder and customs agent fees',
  6324: 'Professional fees',
  6325: "Legal document and litigation costs'actes et de contentieux",
  6328: 'Miscellaneous fees',
  633: 'STAFF TRAINING AND DEVELOPMENT EXPENSES',
  634: 'ROYALTIES FOR PATENTS, LICENCES, SOFTWARE AND SIMILAR RIGHTS',
  6342: 'Royalties for patents, licences and concessions',
  6343: 'Software licence fees and royalties',
  6344: 'Trademark royalties',
  635: 'MEMBERSHIP DUES AND PROFESSIONAL CONTRIBUTIONS',
  6351: 'Contributions',
  6358: 'Various other contributions',
  637: "FEES FOR TEMPORARY AND SECONDED EXTERNAL STAFF L'ENTREPRISE",
  6371: 'Temporary staff',
  6372: "Seconded or loaned staff costs'entreprise",
  638: 'OTHER EXTERNAL CHARGES',
  6381: 'Staff recruitment costs',
  6382: 'Removal and relocation costs',
  6383: 'Receptions',
  6384: 'Missions',

  // ────────── 64 TAXES AND DUTIES ──────────
  64: 'TAXES AND DUTIES',
  641: 'DIRECT TAXES AND DUTIES',
  6411: 'Property taxes and related levies',
  6412: 'Business licences (patente) and related taxes',
  6413: 'Payroll and salary taxes',
  6414: "Apprenticeship levy'apprentissage",
  6415: 'Continuing professional training levy',
  6418: 'Other direct taxes',
  645: 'INDIRECT TAXES AND DUTIES',
  646: "REGISTRATION DUTIES AND STAMP TAXES D'ENREGISTREMENT",
  6461: 'Transfer / conveyance duties',
  6462: 'Stamp duties',
  6463: 'Company vehicle tax',
  6464: 'Road tax stickers',
  6468: 'Other registration duties',
  647: 'TAX PENALTIES AND FINES',
  6471: "Assessment penalties'assiette, impôts directs",
  6472: "Assessment penalties'assiette, impôts indirects",
  6473: 'Collection penalties',
  6474: 'Collection penalties',
  6478: 'Other tax and criminal fines',
  648: 'OTHER TAXES AND LEVIES',

  // ────────── 65 OTHER OPERATING CHARGES ──────────
  65: 'OTHER CHARGES',
  651: 'LOSSES ON WRITE-OFF OF CUSTOMER AND OTHER RECEIVABLES',
  6511: 'Customers',
  6515: 'Other debtors',
  652: 'SHARE OF RESULT ON JOINT VENTURE TRANSACTIONS',
  6521: 'Share of profits transferred',
  6525: 'Losses allocated by transfer',
  653: 'RESULT REVERSAL ON PARTIAL COMPLETION OF MULTI-YEAR CONTRACTS',
  654: "NET BOOK VALUE OF FIXED ASSETS SOLD IN ORDINARY COURSE OF BUSINESS D'IMMOBILISATIONS",
  658: 'MISCELLANEOUS OTHER CHARGES',
  6581: "Directors fees and other board remuneration'administrateurs",
  6582: 'Donations',
  6583: 'Sponsorship',
  659: "SHORT-TERM OPERATING RISK PROVISIONS (CHARGE) D'EXPLOITATION",
  6591: 'Short-term operating risk provisions charged',
  6593: 'on inventory',
  6594: 'on receivables',
  6598: 'Other provisions charged',

  // ────────── 66 PERSONNEL EXPENSES ──────────
  66: 'PERSONNEL EXPENSES',
  661: 'DIRECT REMUNERATION PAID TO LOCAL (NATIONAL) STAFF',
  6611: 'Salaries, wages and commissions',
  6612: 'Bonuses and performance awards',
  6613: 'Paid leave',
  6614: "Notice, redundancy and job-search allowances'embauche",
  6615: 'Sickness allowances paid',
  6616: 'Family supplement allowance',
  6617: 'Benefits in kind',
  6618: 'Other direct remuneration',
  662: 'DIRECT REMUNERATION PAID TO EXPATRIATE STAFF',
  6621: 'Salaries, wages and commissions',
  6622: 'Bonuses and performance awards',
  6623: 'Paid leave',
  6624: "Notice, redundancy and job-search allowances'embauche",
  6625: 'Sickness allowances paid',
  6626: 'Family supplement allowance',
  6627: 'Benefits in kind',
  6628: 'Other direct remuneration',
  663: 'LUMP-SUM ALLOWANCES PAID TO STAFF',
  6631: 'Housing allowances',
  6632: 'Representation / entertainment allowances',
  6633: "Expatriation allowances'expatriation",
  6638: 'Other allowances and benefits',
  664: 'EMPLOYER SOCIAL SECURITY AND SOCIAL CHARGES',
  6641: 'Social charges on national staff remuneration',
  6642: 'Social charges on expatriate staff remuneration',
  666: "SOLE TRADER L'EXPLOITANT INDIVIDUEL",
  6661: "Sole trader'exploitant",
  6662: 'Sole trader',
  667: 'COST TRANSFER FOR EXTERNAL STAFF (TEMPORARY AND SECONDED)',
  6671: 'Temporary staff',
  6672: "Seconded staff cost transferred'entreprise",
  668: 'OTHER EMPLOYEE-RELATED SOCIAL EXPENSES',
  6681: "Payments to trade unions and works councils'entreprise, d'établissement",
  6682: "Payments to health and safety committees'hygiène et de sécurité",
  6683: 'Payments to other social welfare programs',
  6684: 'Occupational health and pharmacy costs',

  // ────────── 67 FINANCIAL EXPENSES AND EQUIVALENT ──────────
  67: 'FINANCE COSTS AND SIMILAR CHARGES',
  671: 'INTEREST EXPENSE ON BORROWINGS',
  6711: 'Interest on bond loans',
  6712: 'Interest on bank loans',
  6713: 'Interest on participation-related debts',
  672: 'FINANCE CHARGES WITHIN LEASE RENTALS',
  6721: 'Finance charges in real estate lease rentals',
  6722: 'Finance charges in movable asset lease rentals',
  6723: 'Finance charges in other lease rentals',
  673: 'SETTLEMENT DISCOUNTS GRANTED TO CUSTOMERS',
  674: 'OTHER INTEREST EXPENSES',
  6741: 'Interest on advances received and credit deposits',
  6742: 'Interest on blocked current accounts',
  6743: 'Interest on guaranteed/secured debt obligations',
  6744: 'Late payment interest on trade payables',
  6745: "Bank interest and treasury/discounting charges'escompte",
  6748: 'Interest on miscellaneous debts',
  675: 'BILL DISCOUNTING CHARGES (DISCOUNT ON COMMERCIAL PAPER)',
  676: 'FOREIGN EXCHANGE LOSSES',
  677: 'LOSSES ON DISPOSAL OF SHORT-TERM INVESTMENT SECURITIES',
  678: 'LOSSES ON FINANCIAL RISKS',
  6781: 'Losses on life annuity financial risks',
  6782: 'Losses on financial operations',
  6784: 'Losses on treasury/derivative instruments',
  679: 'FINANCIAL RISK PROVISIONS (CHARGE)',
  6791: 'Provisions for financial risks charged',
  6795: 'Provisions for investment securities impairment charged',
  6798: 'Other financial provisions charged',

  // ────────── 68 DEPRECIATION EXPENSES ──────────
  68: 'DEPRECIATION AND AMORTISATION CHARGES',
  681: "OPERATING DEPRECIATION AND AMORTISATION CHARGES D'EXPLOITATION",
  6811: 'Amortisation of deferred charges',
  6812: 'Amortisation of intangible assets',
  6813: 'Depreciation of tangible fixed assets',
  687: 'FINANCIAL DEPRECIATION CHARGES',
  6872: 'Amortisation of bond redemption premiums',
  6878: 'Other financial amortisation charges',

  // ────────── 69 PROVISION EXPENSES ──────────
  69: 'PROVISIONS CHARGED (INCREASE IN PROVISIONS)',
  691: "OPERATING PROVISIONS CHARGED D'EXPLOITATION",
  6911: 'Operating provisions for risks and charges',
  6912: 'Provisions for major repairs',
  6913: 'Impairment provisions on intangible assets',
  6914: 'Impairment provisions on tangible assets',
  697: 'FINANCIAL PROVISIONS CHARGED',
  6971: 'Financial provisions for risks and charges',
  6972: 'Impairment provisions on financial assets',
} as const satisfies Plan;

export type Class6AccountCode = keyof typeof class6Accounts;
